### ISSUE TITLE
GLMakie : OpenGL Headless gitlab action

### ISSUE THREAD

**Issue by mananbordia** [JuliaPlots/Makie.jl#1002]
I have tried following headless github action but that didn't worked for me. 
Due to this GLMakie was not precompiled and [CI pipeline](https://gitlab.com/mananbordia/astrodynamics.jl/-/jobs/1303504520) was failed.

 [.gitlab-ci.yml file](https://gitlab.com/mananbordia/astrodynamics.jl/-/blob/master/.gitlab-ci.yml)

```
pages:
  image: julia:1.6
  stage: deploy
  script:
    # workaround for https://github.com/JuliaDocs/Documenter.jl/issues/686
    # workaround for https://github.com/JuliaPlots/Makie.jl/issues/461#issuecomment-850806973
    - apt-get -qq update; apt-get -y install git; apt-get install -y xorg-dev mesa-utils xvfb libgl1 freeglut3-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev
    - |
      julia --project=docs -e '
        using Pkg
        Pkg.develop(PackageSpec(path=pwd()))
        Pkg.instantiate()'
    - julia --project=docs --color=yes docs/make.jl

    - mkdir -p public
    - mv docs/build public/dev
  artifacts:
    paths:
      - public
  only:
    - master
```

How can I resolve this issue ?
