### ISSUE TITLE
compiled makie does not show window

### ISSUE THREAD

**Issue by daviehh** [JuliaPlots/Makie.jl#300]
using `PackageCompiler.compile_incremental(:Makie, :StatsMakie, :AbstractPlotting)`, I'm able to compile and the sample code

```
x = LinRange(0,3pi,200)
y = sin.(x)
@time lin = lines(x, y, padding = (0.0, 0.0), axis = (
            names = (axisnames = ("", ""),),
            grid = (linewidth = (0, 0),),
        ))
```
runs in under a second as opposed to ~20 seconds of the JIT version; however, no plot window is shown, and it just returns (the same code with stock sysimg works as expected)

```
0.390765 seconds (154.33 k allocations: 35.591 MiB, 17.25% gc time)
Scene (960px, 540px):
events:
    window_area: GeometryTypes.HyperRectangle{2,Int64}([0, 0], [0, 0])
    window_dpi: 100.0
    window_open: false
    mousebuttons: Set(AbstractPlotting.Mouse.Button[])
    mouseposition: (0.0, 0.0)
    mousedrag: notpressed
    scroll: (0.0, 0.0)
    keyboardbuttons: Set(AbstractPlotting.Keyboard.Button[])
    unicode_input: Char[]
    dropped_files: String[]
    hasfocus: false
    entered_window: false
plots:
   *Axis2D{...}
   *Lines{...}
subscenes:
   *scene(960px, 540px)

```
